global function Sh_PrecacheWeapons

void function Sh_PrecacheWeapons()
{
	#if SERVER
	// entity player = GetPlayerByIndex( 0 )
	// player.SetPersistentVar( "activeCallsignIconIndex", 56 )
	#endif

	// Commented out weapons are missing script that causes a crash on startup, so don't use them

	PrecacheWeapon( "melee_pilot_arena" )
	PrecacheWeapon( "melee_pilot_emptyhanded" )
	PrecacheWeapon( "melee_pilot_sword" )
	PrecacheWeapon( "melee_titan_punch" )
	PrecacheWeapon( "melee_titan_punch_fighter" )
	PrecacheWeapon( "melee_titan_punch_ion" )
	PrecacheWeapon( "melee_titan_punch_legion" )
	PrecacheWeapon( "melee_titan_punch_northstar" )
	PrecacheWeapon( "melee_titan_punch_scorch" )
	PrecacheWeapon( "melee_titan_punch_tone" )
	PrecacheWeapon( "melee_titan_punch_vanguard" )
	PrecacheWeapon( "melee_titan_sword" )
	PrecacheWeapon( "melee_titan_sword_aoe" )
	PrecacheWeapon( "mp_ability_arc_blast" )
	// PrecacheWeapon( "mp_ability_burncardweapon" )
	PrecacheWeapon( "mp_ability_cloak" )
	PrecacheWeapon( "mp_ability_grapple" )
	PrecacheWeapon( "mp_ability_heal" )
	PrecacheWeapon( "mp_ability_holopilot" )
	PrecacheWeapon( "mp_ability_holopilot_nova" )
	// PrecacheWeapon( "mp_ability_pathchooser" )
	PrecacheWeapon( "mp_ability_shifter" )
	PrecacheWeapon( "mp_ability_shifter_super" )
	PrecacheWeapon( "mp_ability_swordblock" )
	PrecacheWeapon( "mp_ability_timeshift" )
	// PrecacheWeapon( "mp_ability_turretweapon" )
	PrecacheWeapon( "mp_titanability_ammo_swap" )
	PrecacheWeapon( "mp_titanability_basic_block" )
	PrecacheWeapon( "mp_titanability_electric_smoke" )
	PrecacheWeapon( "mp_titanability_gun_shield" )
	PrecacheWeapon( "mp_titanability_hover" )
	PrecacheWeapon( "mp_titanability_laser_trip" )
	// PrecacheWeapon( "mp_titanability_nuke_eject" )
	PrecacheWeapon( "mp_titanability_particle_wall" )
	PrecacheWeapon( "mp_titanability_phase_dash" )
	PrecacheWeapon( "mp_titanability_power_shot" )
	PrecacheWeapon( "mp_titanability_rearm" )
	PrecacheWeapon( "mp_titanability_rocketeer_ammo_swap" )
	PrecacheWeapon( "mp_titanability_slow_trap" )
	PrecacheWeapon( "mp_titanability_smoke" )
	PrecacheWeapon( "mp_titanability_sonar_pulse" )
	PrecacheWeapon( "mp_titanability_tether_trap" )
	PrecacheWeapon( "mp_titanability_timeshift" )
	PrecacheWeapon( "mp_titancore_amp_core" )
	PrecacheWeapon( "mp_titancore_dash_core" )
	PrecacheWeapon( "mp_titancore_flame_wave" )
	PrecacheWeapon( "mp_titancore_flight_core" )
	PrecacheWeapon( "mp_titancore_laser_cannon" )
	PrecacheWeapon( "mp_titancore_salvo_core" )
	PrecacheWeapon( "mp_titancore_shift_core" )
	PrecacheWeapon( "mp_titancore_siege_mode" )
	PrecacheWeapon( "mp_titancore_upgrade" )
	PrecacheWeapon( "mp_titanweapon_arc_wave" )
	PrecacheWeapon( "mp_titanweapon_dumbfire_rockets" )
	PrecacheWeapon( "mp_titanweapon_flame_wall" )
	PrecacheWeapon( "mp_titanweapon_flightcore_rockets" )
	PrecacheWeapon( "mp_titanweapon_heat_shield" )
	PrecacheWeapon( "mp_titanweapon_homing_rockets" )
	PrecacheWeapon( "mp_titanweapon_laser_lite" )
	PrecacheWeapon( "mp_titanweapon_leadwall" )
	PrecacheWeapon( "mp_titanweapon_meteor" )
	PrecacheWeapon( "mp_titanweapon_orbital_strike" )
	PrecacheWeapon( "mp_titanweapon_particle_accelerator" )
	PrecacheWeapon( "mp_titanweapon_predator_cannon" )
	PrecacheWeapon( "mp_titanweapon_predator_cannon_siege" )
	PrecacheWeapon( "mp_titanweapon_rocketeer_rocketstream" )
	PrecacheWeapon( "mp_titanweapon_salvo_rockets" )
	PrecacheWeapon( "mp_titanweapon_shoulder_rockets" )
	PrecacheWeapon( "mp_titanweapon_sniper" )
	PrecacheWeapon( "mp_titanweapon_sticky_40mm" )
	PrecacheWeapon( "mp_titanweapon_stun_laser" )
	PrecacheWeapon( "mp_titanweapon_tracker_rockets" )
	PrecacheWeapon( "mp_titanweapon_vortex_shield" )
	PrecacheWeapon( "mp_titanweapon_vortex_shield_ion" )
	PrecacheWeapon( "mp_titanweapon_xo16" )
	PrecacheWeapon( "mp_titanweapon_xo16_shorty" )
	PrecacheWeapon( "mp_titanweapon_xo16_vanguard" )
	PrecacheWeapon( "mp_turretweapon_blaster" )
	PrecacheWeapon( "mp_turretweapon_plasma" )
	PrecacheWeapon( "mp_turretweapon_sentry" )
	PrecacheWeapon( "mp_weapon_alternator_smg" )
	PrecacheWeapon( "mp_weapon_arc_launcher" )
	// PrecacheWeapon( "mp_weapon_arc_trap" )
	PrecacheWeapon( "mp_weapon_arena1" )
	PrecacheWeapon( "mp_weapon_arena2" )
	PrecacheWeapon( "mp_weapon_arena3" )
	PrecacheWeapon( "mp_weapon_autopistol" )
	PrecacheWeapon( "mp_weapon_car" )
	PrecacheWeapon( "mp_weapon_defender" )
	PrecacheWeapon( "mp_weapon_deployable_cover" )
	PrecacheWeapon( "mp_weapon_dmr" )
	PrecacheWeapon( "mp_weapon_doubletake" )
	PrecacheWeapon( "mp_weapon_dronebeam" )
	PrecacheWeapon( "mp_weapon_droneplasma" )
	PrecacheWeapon( "mp_weapon_dronerocket" )
	PrecacheWeapon( "mp_weapon_engineer_combat_drone" )
	PrecacheWeapon( "mp_weapon_engineer_turret" )
	PrecacheWeapon( "mp_weapon_epg" )
	PrecacheWeapon( "mp_weapon_esaw" )
	PrecacheWeapon( "mp_weapon_frag_drone" )
	PrecacheWeapon( "mp_weapon_frag_grenade" )
	PrecacheWeapon( "mp_weapon_g2" )
	PrecacheWeapon( "mp_weapon_grenade_electric_smoke" )
	PrecacheWeapon( "mp_weapon_grenade_emp" )
	PrecacheWeapon( "mp_weapon_grenade_gravity" )
	PrecacheWeapon( "mp_weapon_grenade_sonar" )
	PrecacheWeapon( "mp_weapon_gunship_launcher" )
	PrecacheWeapon( "mp_weapon_gunship_missile" )
	PrecacheWeapon( "mp_weapon_gunship_turret" )
	PrecacheWeapon( "mp_weapon_hard_cover" )
	PrecacheWeapon( "mp_weapon_hemlok" )
	PrecacheWeapon( "mp_weapon_hemlok_smg" )
	PrecacheWeapon( "mp_weapon_lmg" )
	PrecacheWeapon( "mp_weapon_lstar" )
	PrecacheWeapon( "mp_weapon_mastiff" )
	PrecacheWeapon( "mp_weapon_mega_turret" )
	// PrecacheWeapon( "mp_weapon_mega_turret_s2s" )
	PrecacheWeapon( "mp_weapon_mgl" )
	PrecacheWeapon( "mp_weapon_npc_rocket_launcher" )
	PrecacheWeapon( "mp_weapon_pulse_lmg" )
	PrecacheWeapon( "mp_weapon_r97" )
	PrecacheWeapon( "mp_weapon_rocket_launcher" )
	PrecacheWeapon( "mp_weapon_rspn101" )
	PrecacheWeapon( "mp_weapon_rspn101_og" )
	PrecacheWeapon( "mp_weapon_satchel" )
	PrecacheWeapon( "mp_weapon_semipistol" )
	PrecacheWeapon( "mp_weapon_shotgun" )
	PrecacheWeapon( "mp_weapon_shotgun_doublebarrel" )
	PrecacheWeapon( "mp_weapon_shotgun_pistol" )
	PrecacheWeapon( "mp_weapon_smart_pistol" )
	PrecacheWeapon( "mp_weapon_smart_pistol_og" )
	PrecacheWeapon( "mp_weapon_smr" )
	PrecacheWeapon( "mp_weapon_sniper" )
	PrecacheWeapon( "mp_weapon_softball" )
	PrecacheWeapon( "mp_weapon_spectre_spawner" )
	PrecacheWeapon( "mp_weapon_super_spectre" )
	PrecacheWeapon( "mp_weapon_thermite_grenade" )
	PrecacheWeapon( "mp_weapon_turretlaser_mega" )
	PrecacheWeapon( "mp_weapon_turretlaser_mega_fort_war" )
	PrecacheWeapon( "mp_weapon_turretplasma" )
	PrecacheWeapon( "mp_weapon_turretplasma_mega" )
	PrecacheWeapon( "mp_weapon_turret_tday" )
	PrecacheWeapon( "mp_weapon_vinson" )
	PrecacheWeapon( "mp_weapon_wingman" )
	PrecacheWeapon( "mp_weapon_wingman_n" )
	PrecacheWeapon( "mp_weapon_yh803" )
	PrecacheWeapon( "mp_weapon_yh803_bullet" )
	PrecacheWeapon( "mp_weapon_yh803_bullet_overcharged" )
	PrecacheWeapon( "sp_weapon_arc_tool" )
	// PrecacheWeapon( "sp_weapon_swarm_rockets_s2s" )
	// PrecacheWeapon( "sp_weapon_viperbossrockets_s2s" )

}
